#!/bin/bash

set -o errexit

set -o nounset

worker_ready() {
    celery -A hr_project inspect ping
}

until worker_ready; do
    >&2 echo 'Celery workers not available :-('
    sleep 1

done
>&2 echo 'Celery workers are available and ready :-)'

celery -A hr_project  \
    --broker="${CELERY_BROKER}" \
    flower
